{% set name = "mpacklog" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpacklog-{{ version }}.tar.gz
  sha256: bf8af84a193c4655ee33e4e41451811b69a0689acacda5e88f3adf837635e113

build:
  entry_points:
    - mpacklog = mpacklog.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8
    - aiofiles >=0.7.0
    - loop-rate-limiters >=1.0.0
    - msgpack-python >=1.0.2

test:
  imports:
    - mpacklog
  commands:
    - pip check
    - mpacklog --help
  requires:
    - pip

about:
  summary: Log dictionaries to file using the MessagePack serialization format.
  dev_url: https://github.com/stephane-caron/mpacklog.py
  license: Apache-2.0
  license_file: LICENSE
  home: https://pypi.org/project/mpacklog

extra:
  recipe-maintainers:
    - stephane-caron
