{% set name = "mpacklog" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpacklog-{{ version }}.tar.gz
  sha256: 00e08f48a04222172480419b9d5be80b597818b87b07d8db152128387d8784d3

build:
  entry_points:
    - mpacklog = mpacklog.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8
    - aiofiles >=0.7.0
    - loop-rate-limiters >=1.0.0
    - msgpack-python >=1.0.2

test:
  imports:
    - mpacklog
  commands:
    - pip check
    - mpacklog --help
  requires:
    - pip

about:
  summary: Log dictionaries to file using the MessagePack serialization format.
  dev_url: https://github.com/tasts-robots/mpacklog.py
  license: Apache-2.0
  license_file: LICENSE
  home: https://pypi.org/project/mpacklog

extra:
  recipe-maintainers:
    - stephane-caron
